# Generated by Django 3.2.6 on 2021-08-17 20:05

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='ФИО')),
                ('position', models.CharField(max_length=255, verbose_name='Должность')),
                ('date', models.DateTimeField(verbose_name='Дата приема на работу')),
                ('earnings', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='Заработная плата')),
                ('inform', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='Информация о выплаченной зп')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='YUY', to='app_1.employee')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
